In [9]:
import pandas as pd

In [10]:
df_2015=pd.read_csv("marathon_results_2015.csv")
df_2016=pd.read_csv("marathon_results_2016.csv")
df_2017=pd.read_csv("marathon_results_2017.csv")

In [11]:
#concatinate the dataset into the single dataframe
df=pd.concat([df_2015,df_2016,df_2017])

In [13]:
# get the total number of rows in orignal dataframe
original_row_count=len(df)
original_row_count

79638

In [14]:
# perform simple random sampling (selecting 1/10th of the records)
sample_df=df.sample(frac=0.1,random_state=42)
sample_df

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
24038,24038.0,31350,"Labonte, Laura R.",34,F,Charlestown,MA,USA,NaN,NaN,...,3:22:19,3:56:22,4:29:25,0:10:49,-,4:43:30,24039,10561,5235,NaN
20218,20218.0,21352,"Vargas, Mario",64,M,Shaker Heights,OH,USA,NaN,NaN,...,2:52:26,3:24:14,3:54:58,0:09:28,-,4:08:04,20219,11836,568,NaN
23755,23755.0,27235,"Wilkins, Stephen D.",53,M,Dorchester,MA,USA,NaN,NaN,...,3:14:37,3:49:59,4:24:08,0:10:40,-,4:39:30,23756,13348,1896,NaN
1447,1447.0,4337,"Johnson, David T",32,M,Brandon,FL,USA,NaN,NaN,...,2:00:46,2:21:31,2:43:11,0:06:39,-,2:54:17,1448,1376,1108,NaN
25121,NaN,26089,"Bashor, Mari W",67,F,Sacramento,CA,USA,NaN,NaN,...,3:35:49,4:17:13,4:56:18,0:11:58,5:13:34,5:13:34,25121,11285,87,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23322,23322.0,11427,"Silwal, Suman",45,M,Pelham,AL,USA,NaN,NaN,...,2:47:50,3:31:03,4:16:56,0:10:29,-,4:34:32,23323,13155,2301,NaN
5102,NaN,10536,"Baganz, Paul",62,M,Fond Du Lac,WI,USA,NaN,NaN,...,2:21:55,2:46:20,3:10:05,0:07:40,3:20:41,3:20:41,5103,4349,25,NaN
12821,12821.0,12730,"Strutz, Nicole",22,F,Two Rivers,WI,USA,NaN,NaN,...,2:37:04,3:09:17,3:39:22,0:08:48,-,3:50:20,12823,4327,2843,NaN
13241,NaN,21185,"Greengrass, Suzie",45,F,Cary,NC,USA,NaN,NaN,...,2:39:19,3:08:02,3:35:21,0:08:42,3:47:50,3:47:50,13241,4490,482,NaN
8893,8893.0,13873,"Fitzgerald, Vanessa",38,F,Long Island City,NY,USA,NaN,NaN,...,2:26:48,2:51:30,3:15:28,0:07:53,-,3:26:22,8894,1827,1489,NaN

In [15]:
# Get the total number of rows in the sampled dataframe
sample_row_count=len(sample_df)
sample_row_count

7964

In [16]:
original_row_count

79638

In [17]:
print("First few rows of og dataframe: ")
print(df.head())
print("\n First few rows of the sampled dataframe: ")
print(sample_df.head())

First few rows of og dataframe:
   Unnamed: 0 Bib                   Name  Age M/F         City State Country  \
0         0.0   3         Desisa, Lelisa   25   M         Ambo   NaN     ETH
1         1.0   4  Tsegay, Yemane Adhane   30   M  Addis Ababa   NaN     ETH
2         2.0   8         Chebet, Wilson   29   M     Marakwet   NaN     KEN
3         3.0  11       Kipyego, Bernard   28   M      Eldoret   NaN     KEN
4         4.0  10          Korir, Wesley   32   M       Kitale   NaN     KEN

  Citizen Unnamed: 9  ...      30K      35K      40K     Pace Proj Time  \
0     NaN        NaN  ...  1:32:00  1:47:59  2:02:39  0:04:56         -
1     NaN        NaN  ...  1:31:59  1:47:59  2:02:42  0:04:58         -
2     NaN        NaN  ...  1:32:00  1:47:59  2:03:01  0:04:59         -
3     NaN        NaN  ...  1:32:00  1:48:03  2:03:47  0:05:00         -
4     NaN        NaN  ...  1:32:00  1:47:59  2:03:27  0:05:00         -

  Official Time Overall Gender Division Unnamed: 8
0       2:09:17       1      1        1        NaN
1       2:09:48       2      2        2        NaN
2       2:10:22       3      3        3        NaN
3       2:10:47       4      4        4        NaN
4       2:10:49       5      5        5        NaN

[5 rows x 26 columns]

 First few rows of the sampled dataframe:
       Unnamed: 0    Bib                 Name  Age M/F            City State  \
24038     24038.0  31350    Labonte, Laura R.   34   F     Charlestown    MA
20218     20218.0  21352        Vargas, Mario   64   M  Shaker Heights    OH
23755     23755.0  27235  Wilkins, Stephen D.   53   M      Dorchester    MA
1447       1447.0   4337     Johnson, David T   32   M         Brandon    FL
25121         NaN  26089       Bashor, Mari W   67   F      Sacramento    CA

      Country Citizen Unnamed: 9  ...      30K      35K      40K     Pace  \
24038     USA     NaN        NaN  ...  3:22:19  3:56:22  4:29:25  0:10:49
20218     USA     NaN        NaN  ...  2:52:26  3:24:14  3:54:58  0:09:28
23755     USA     NaN        NaN  ...  3:14:37  3:49:59  4:24:08  0:10:40
1447      USA     NaN        NaN  ...  2:00:46  2:21:31  2:43:11  0:06:39
25121     USA     NaN        NaN  ...  3:35:49  4:17:13  4:56:18  0:11:58

      Proj Time Official Time Overall Gender Division Unnamed: 8
24038         -       4:43:30   24039  10561     5235        NaN
20218         -       4:08:04   20219  11836      568        NaN
23755         -       4:39:30   23756  13348     1896        NaN
1447          -       2:54:17    1448   1376     1108        NaN
25121   5:13:34       5:13:34   25121  11285       87        NaN

[5 rows x 26 columns]

In [21]:
print(f"Number of rows of og dataframe: {original_row_count}")
print(f"\nNumber of  rows of the sampled dataframe: {sample_row_count} ")

Number of rows of og dataframe: 79638

Number of  rows of the sampled dataframe: 7964

In [26]:
sample_df = df.iloc[::7]
sample_df

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,ETH,NaN,NaN,...,1:32:00,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,NaN
7,7.0,1,"Keflezighi, Meb",39,M,San Diego,CA,USA,NaN,NaN,...,1:31:59,1:47:59,2:04:58,0:05:04,-,2:12:42,8,8,8,NaN
14,14.0,76,"Goffi, Danilo",42,M,Parabiago - Milan,NaN,ITA,NaN,NaN,...,1:38:02,1:54:55,2:11:25,0:05:18,-,2:18:44,15,15,1,NaN
21,21.0,32,"Zywicki, Benjamin P.",26,M,Louisville,CO,USA,NaN,NaN,...,1:38:46,1:56:05,2:13:25,0:05:24,-,2:21:10,22,22,21,NaN
28,28.0,106,"Glaz, Daniel",32,M,Chicago,IL,USA,NaN,NaN,...,1:42:19,1:59:50,2:17:03,0:05:32,-,2:24:44,29,29,27,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26376,26376.0,25766,"Miranda, Denisse C.",40,F,Long Beach,CA,USA,NaN,NaN,...,4:23:21,5:07:56,5:49:53,0:14:04,-,6:08:48,26378,11963,1852,NaN
26383,26383.0,25182,"Trang, Danh",30,M,San Francisco,CA,USA,NaN,MI,...,4:14:48,5:06:21,5:56:00,0:14:15,-,6:13:26,26385,14417,4766,NaN
26390,26390.0,28988,"Taylor, Robert",56,M,Ft Lauderdale,FL,USA,NaN,NaN,...,4:19:45,5:10:26,6:02:15,0:14:35,-,6:22:13,26392,14423,1536,NaN
26397,26397.0,15536,"Coffman, Steven D.",69,M,East Sandwich,MA,USA,NaN,NaN,...,4:43:52,5:37:23,6:24:02,0:15:21,-,6:42:04,26399,14429,425,NaN
26404,26404.0,25141,"Quinn, Adam H.",19,M,Belmont,MI,USA,NaN,MI,...,4:42:59,5:33:15,6:42:51,0:16:12,-,7:04:33,26406,14435,4773,NaN

In [25]:
sample_df = df.iloc[::7,:]
sample_df

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division,Unnamed: 8
0,0.0,3,"Desisa, Lelisa",25,M,Ambo,NaN,ETH,NaN,NaN,...,1:32:00,1:47:59,2:02:39,0:04:56,-,2:09:17,1,1,1,NaN
7,7.0,1,"Keflezighi, Meb",39,M,San Diego,CA,USA,NaN,NaN,...,1:31:59,1:47:59,2:04:58,0:05:04,-,2:12:42,8,8,8,NaN
14,14.0,76,"Goffi, Danilo",42,M,Parabiago - Milan,NaN,ITA,NaN,NaN,...,1:38:02,1:54:55,2:11:25,0:05:18,-,2:18:44,15,15,1,NaN
21,21.0,32,"Zywicki, Benjamin P.",26,M,Louisville,CO,USA,NaN,NaN,...,1:38:46,1:56:05,2:13:25,0:05:24,-,2:21:10,22,22,21,NaN
28,28.0,106,"Glaz, Daniel",32,M,Chicago,IL,USA,NaN,NaN,...,1:42:19,1:59:50,2:17:03,0:05:32,-,2:24:44,29,29,27,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26376,26376.0,25766,"Miranda, Denisse C.",40,F,Long Beach,CA,USA,NaN,NaN,...,4:23:21,5:07:56,5:49:53,0:14:04,-,6:08:48,26378,11963,1852,NaN
26383,26383.0,25182,"Trang, Danh",30,M,San Francisco,CA,USA,NaN,MI,...,4:14:48,5:06:21,5:56:00,0:14:15,-,6:13:26,26385,14417,4766,NaN
26390,26390.0,28988,"Taylor, Robert",56,M,Ft Lauderdale,FL,USA,NaN,NaN,...,4:19:45,5:10:26,6:02:15,0:14:35,-,6:22:13,26392,14423,1536,NaN
26397,26397.0,15536,"Coffman, Steven D.",69,M,East Sandwich,MA,USA,NaN,NaN,...,4:43:52,5:37:23,6:24:02,0:15:21,-,6:42:04,26399,14429,425,NaN
26404,26404.0,25141,"Quinn, Adam H.",19,M,Belmont,MI,USA,NaN,MI,...,4:42:59,5:33:15,6:42:51,0:16:12,-,7:04:33,26406,14435,4773,NaN

In [38]:
# how good is our sampling?
# same code as before for sample random sampling ....
df[['Hours','Minutes','Seconds']] = df['Official Time'].str.split(":",expand=True)
df['Hours']=df['Hours'].astype(int)
df['Minutes']=df['Minutes'].astype(int)
df['Seconds']=df['Seconds'].astype(int)

df['finish_time_in_seconds']=(
    df['Hours']*3600+
    df['Minutes']*60+
    df['Seconds']
)
df['finish_time_in_seconds']

0         7757
1         7788
2         7822
3         7847
4         7849
         ...
26405    25779
26406    26219
26407    26377
26408    26444
26409    28694
Name: finish_time_in_seconds, Length: 79638, dtype: int64

In [39]:
# Split the Pace string into two new columns
df[['Pace_Minutes', 'Pace_Seconds']] = df['Pace'].str.split(':', expand=True).astype(int)

# Calculate total seconds (Pace usually doesn't have an 'Hours' component)
df['Pace_in_seconds'] = (
    df['Pace_Minutes'] * 60 + 
    df['Pace_Seconds']
)

ValueError: Columns must be same length as key