In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from scipy.stats import zscore

In [11]:
df=pd.read_csv("billionaires_2022.csv")
df

,year,month,rank,net_worth,last_name,first_name,full_name,birth_date,age,gender,country_of_citizenship,country_of_residence,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
0,2022,4,1,219.0 B,Musk,Elon,Elon Musk,1971-06-28,50.0,Male,United States,United States,Austin,Automotive,['Automotive'],Tesla,CEO,True,Increased
1,2022,4,2,171.0 B,Bezos,Jeff,Jeff Bezos,1964-01-12,58.0,Male,United States,United States,Seattle,Technology,['Technology'],Amazon,Chairman and Founder,True,Decreased
2,2022,4,3,158.0 B,Arnault,Bernard,Bernard Arnault & family,1949-03-05,73.0,Male,France,France,Paris,Fashion & Retail,['Fashion & Retail'],LVMH Moet Hennessy Louis Vuitton,Chairman and CEO,False,Increased
3,2022,4,4,129.0 B,Gates,Bill,Bill Gates,1955-10-28,66.0,Male,United States,United States,Medina,Technology,['Technology'],Bill & Melinda Gates Foundation,Cofounder,True,Increased
4,2022,4,5,118.0 B,Buffett,Warren,Warren Buffett,1930-08-30,91.0,Male,United States,United States,Omaha,Finance & Investments,['Finance & Investments'],Berkshire Hathaway Inc. (Cl A),CEO,True,Increased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2663,2022,4,2578,1.0 B,Zhang,Yuqiang,Zhang Yuqiang,1955-09-01,66.0,Male,China,China,Tongxiang,Manufacturing,['Manufacturing'],NaN,NaN,True,Remained Even
2664,2022,4,2578,1.0 B,Zhou,Ruxin,Zhou Ruxin,1963-03-01,59.0,Male,China,China,Beijing,Technology,['Technology'],NaN,NaN,True,Decreased
2665,2022,4,2578,1.0 B,Zhou,Wen,Zhou Wen & family,1965-03-06,57.0,Male,China,China,Shanghai,Manufacturing,['Manufacturing'],NaN,NaN,True,Decreased
2666,2022,4,2578,1.0 B,Zhou,Yifeng,Zhou Yifeng & family,1978-07-11,43.0,Female,China,China,Zhangjiagang,Energy,['Energy'],NaN,NaN,True,Decreased
2667,2022,4,2578,1.0 B,Zhuang,Kuilong,Zhuang Kuilong & family,1962-06-15,59.0,Male,China,China,Jiaxing,Manufacturing,['Manufacturing'],NaN,NaN,True,Decreased

In [13]:
df['net_worth']=df['net_worth'].str.replace('$','',regex=False)
df['net_worth']=df['net_worth'].str.replace('B','',regex=False)
df['net_worth']=pd.to_numeric(df['net_worth'],errors='coerce')
df=df.dropna(subset=['net_worth'])

In [14]:
df

,year,month,rank,net_worth,last_name,first_name,full_name,birth_date,age,gender,country_of_citizenship,country_of_residence,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
0,2022,4,1,219.0,Musk,Elon,Elon Musk,1971-06-28,50.0,Male,United States,United States,Austin,Automotive,['Automotive'],Tesla,CEO,True,Increased
1,2022,4,2,171.0,Bezos,Jeff,Jeff Bezos,1964-01-12,58.0,Male,United States,United States,Seattle,Technology,['Technology'],Amazon,Chairman and Founder,True,Decreased
2,2022,4,3,158.0,Arnault,Bernard,Bernard Arnault & family,1949-03-05,73.0,Male,France,France,Paris,Fashion & Retail,['Fashion & Retail'],LVMH Moet Hennessy Louis Vuitton,Chairman and CEO,False,Increased
3,2022,4,4,129.0,Gates,Bill,Bill Gates,1955-10-28,66.0,Male,United States,United States,Medina,Technology,['Technology'],Bill & Melinda Gates Foundation,Cofounder,True,Increased
4,2022,4,5,118.0,Buffett,Warren,Warren Buffett,1930-08-30,91.0,Male,United States,United States,Omaha,Finance & Investments,['Finance & Investments'],Berkshire Hathaway Inc. (Cl A),CEO,True,Increased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2663,2022,4,2578,1.0,Zhang,Yuqiang,Zhang Yuqiang,1955-09-01,66.0,Male,China,China,Tongxiang,Manufacturing,['Manufacturing'],NaN,NaN,True,Remained Even
2664,2022,4,2578,1.0,Zhou,Ruxin,Zhou Ruxin,1963-03-01,59.0,Male,China,China,Beijing,Technology,['Technology'],NaN,NaN,True,Decreased
2665,2022,4,2578,1.0,Zhou,Wen,Zhou Wen & family,1965-03-06,57.0,Male,China,China,Shanghai,Manufacturing,['Manufacturing'],NaN,NaN,True,Decreased
2666,2022,4,2578,1.0,Zhou,Yifeng,Zhou Yifeng & family,1978-07-11,43.0,Female,China,China,Zhangjiagang,Energy,['Energy'],NaN,NaN,True,Decreased
2667,2022,4,2578,1.0,Zhuang,Kuilong,Zhuang Kuilong & family,1962-06-15,59.0,Male,China,China,Jiaxing,Manufacturing,['Manufacturing'],NaN,NaN,True,Decreased

In [29]:
import pandas as pd
from scipy.stats import zscore
df['net_worth_zscore'] = zscore(df['net_worth'])
df['net_worth_percentile'] = df['net_worth_zscore'].rank(pct=True) * 100
net_worth_mean = df['net_worth'].mean()
net_worth_std = df['net_worth'].std()
print(f"mean of networth: {net_worth_mean:.2f} B")
print(f"standard deviation of networth: {net_worth_std:.2f} B")
print(df.head())
print(df.tail())

mean of networth: 4.76 B
standard deviation of networth: 10.54 B
   year  month  rank  net_worth last_name first_name  \
0  2022      4     1      219.0      Musk       Elon
1  2022      4     2      171.0     Bezos       Jeff
2  2022      4     3      158.0   Arnault    Bernard
3  2022      4     4      129.0     Gates       Bill
4  2022      4     5      118.0   Buffett     Warren

                  full_name  birth_date   age gender  ...  \
0                 Elon Musk  1971-06-28  50.0   Male  ...
1                Jeff Bezos  1964-01-12  58.0   Male  ...
2  Bernard Arnault & family  1949-03-05  73.0   Male  ...
3                Bill Gates  1955-10-28  66.0   Male  ...
4            Warren Buffett  1930-08-30  91.0   Male  ...

  country_of_residence city_of_residence      business_category  \
0        United States            Austin             Automotive
1        United States           Seattle             Technology
2               France             Paris       Fashion & Retail
3        United States            Medina             Technology
4        United States             Omaha  Finance & Investments

         business_industries                 organization_name  \
0             ['Automotive']                             Tesla
1             ['Technology']                            Amazon
2       ['Fashion & Retail']  LVMH Moet Hennessy Louis Vuitton
3             ['Technology']   Bill & Melinda Gates Foundation
4  ['Finance & Investments']    Berkshire Hathaway Inc. (Cl A)

  position_in_organization self_made  wealth_status net_worth_zscore  \
0                      CEO      True      Increased        20.329033
1     Chairman and Founder      True      Decreased        15.774308
2         Chairman and CEO     False      Increased        14.540737
3                Cofounder      True      Increased        11.788924
4                      CEO      True      Increased        10.745132

   net_worth_percentile
0            100.000000
1             99.962519
2             99.925037
3             99.887556
4             99.850075

[5 rows x 21 columns]
      year  month  rank  net_worth last_name first_name  \
2663  2022      4  2578        1.0     Zhang    Yuqiang
2664  2022      4  2578        1.0      Zhou      Ruxin
2665  2022      4  2578        1.0      Zhou        Wen
2666  2022      4  2578        1.0      Zhou     Yifeng
2667  2022      4  2578        1.0    Zhuang    Kuilong

                    full_name  birth_date   age  gender  ...  \
2663            Zhang Yuqiang  1955-09-01  66.0    Male  ...
2664               Zhou Ruxin  1963-03-01  59.0    Male  ...
2665        Zhou Wen & family  1965-03-06  57.0    Male  ...
2666     Zhou Yifeng & family  1978-07-11  43.0  Female  ...
2667  Zhuang Kuilong & family  1962-06-15  59.0    Male  ...

     country_of_residence city_of_residence business_category  \
2663                China         Tongxiang     Manufacturing
2664                China           Beijing        Technology
2665                China          Shanghai     Manufacturing
2666                China      Zhangjiagang            Energy
2667                China           Jiaxing     Manufacturing

     business_industries organization_name position_in_organization self_made  \
2663   ['Manufacturing']               NaN                      NaN      True
2664      ['Technology']               NaN                      NaN      True
2665   ['Manufacturing']               NaN                      NaN      True
2666          ['Energy']               NaN                      NaN      True
2667   ['Manufacturing']               NaN                      NaN      True

      wealth_status net_worth_zscore  net_worth_percentile
2663  Remained Even         -0.35701              1.724138
2664      Decreased         -0.35701              1.724138
2665      Decreased         -0.35701              1.724138
2666      Decreased         -0.35701              1.724138
2667      Decreased         -0.35701              1.724138

[5 rows x 21 columns]